---
title: "Grade analysis"
author: "Amandine Godefroy"
format: html
---

```{r}
#| message: false
#| warning: false
here::i_am("TP4.Rproj")
library(here)
library(vroom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
```

# Question 1

Data loading
```{r}
#| message: false
grades <- vroom(here("grades.csv"))
```

# Question 2

```{r}
stats_exam <- grades |> summarize(min_exap = min(Exam, na.rm = TRUE), max_exam = max(Exam, na.rm = TRUE), avg_exam = mean(Exam, na.rm = TRUE), med_exam = median(Exam, na.rm = TRUE))

knitr::kable(stats_exam)
```

# Question 3

```{r}
no_exam <- grades |> count(is.na(Exam))
```
There are `r no_exam[2,2]` students who did not take the exam.

# Question 4

Graphical representation of the distribution of grades at the exam.
```{r}
Exam_woNA <- grades |> filter(!is.na(Exam))

Exam_woNA |> ggplot(aes(x = Exam)) +
  geom_histogram(binwidth = 0.5)
```

## Question 5

```{r}
nber_stdts_group <- grades |> count(Group) |> group_by(Group)

knitr::kable(nber_stdts_group)
```

# Question 6

```{r}
grades |> ggplot(aes(x = Group, fill = Group)) +
  geom_bar() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
# Question 7

```{r}
ggplot(grades, aes(x = Exam, fill = Group)) +
  geom_histogram(bins = 20) +
  geom_rug(alpha = 0.03, linewidth = 1.5) +
  facet_wrap(~Group)
```

```{r}
ggplot(grades, aes(x = Exam, y=Group, fill = Group)) +
  geom_boxplot()
```

# Question 8

```{r}
na_exam_per_group <- grades %>%
  group_by(Group) %>%
  summarise(nber_na_exam = sum(is.na(Exam)))

knitr::kable(na_exam_per_group)
```
# Question 9

```{r}
all_Groups <- inner_join(grades, na_exam_per_group, by=join_by(Group))

ggplot(all_Groups, aes(x = Group, y = nber_na_exam)) +
  geom_col()
```
# Question 10

```{r}
new_grades <- grades %>% pivot_longer(
  cols = Exam | starts_with("MCQ_") | starts_with("Online_MCQ_"),
  names_to = "name",
  values_to = "value"
)
```

# Question 11

```{r}
na_exam_per_student <- new_grades %>%
  group_by(Id) %>%
  summarise(nber_na_grades = sum(is.na(value)))

knitr::kable(na_exam_per_student)
```
# Question 12

```{r}
ggplot(na_exam_per_student, aes(x = nber_na_grades )) + geom_histogram()
```
```{r}
ggplot(na_exam_per_student, aes(x = nber_na_grades))+ geom_density(bw = "SJ") + labs(title = "distribution of the number of missing grades per student")
```

# Question 13

```{r}

exam_new_grades <- new_grades |> filter(str_starts(name, "Exam"))

na_exam_per_group2 <- exam_new_grades %>% group_by(Group) %>%
  summarise(nber_na_exam2 = sum(is.na(value)))

knitr::kable(na_exam_per_group2)
```

# Question 14

```{r}
online_test_new_grades <- new_grades |> filter(str_starts(name, "Online_MCQ_"))

na_online_test_per_student <- online_test_new_grades %>%
  group_by(Id) %>%
  summarise(nber_na_online_test = sum(is.na(value)))

knitr::kable(na_online_test_per_student)
```

# Question 15

```{r}
grades_with_na_online_test <- grades |>
  rowwise() |>
  mutate(na_online_test_per_student2 = sum(is.na(c_across(starts_with("Online_MCQ_")))))
```

```{r}
# Alternative :
grades_with_na_online_test2 <- inner_join(grades, na_online_test_per_student, by = join_by(Id))
```

Graphical representation 
```{r}
ggplot(grades_with_na_online_test, aes(x = Exam, fill = na_online_test_per_student2, color = na_online_test_per_student2)) +
  geom_bar() 
```

# Question 16

```{r}
grades_with_na_mcq_test <- grades |>
  rowwise() |>
  mutate(na_mcq_test_per_student = sum(is.na(c_across(starts_with("MCQ_")))))

grades_with_na_mcq_test2 <- grades_with_na_mcq_test |> mutate(Missed = if (na_mcq_test_per_student == 0) Missed <- FALSE else Missed <- TRUE)

MCQ_missed_per_student <- grades_with_na_mcq_test2 |> select(Id, Missed)

knitr::kable(MCQ_missed_per_student)
```

# Question 17

```{r}
nber_missed_mcq_per_group <- grades_with_na_mcq_test2 |>
  group_by(Group) |>
  count(Missed)

p_na_mcq_group <- inner_join(nber_missed_mcq_per_group, nber_stdts_group, by = join_by(Group), suffix = c("_missed_mcq", "_students"))

p_na_mcq_group_true <- p_na_mcq_group |> filter(Missed==T)

p_na_mcq_group2 <- p_na_mcq_group_true |>
  rowwise() |>
  mutate(P_missed = (n_missed_mcq / n_students) * 100)

p_na_mcq_group3 <- p_na_mcq_group2 |> select(Group, P_missed)

knitr::kable(p_na_mcq_group3)
```
# Question 18

```{r}
# moyenne exam par groupes (en fonction nbre élèves ayant participés à l'exam)
average_exam_per_group <- grades |>
  group_by(Group) |>
  summarise(mean_exam = mean(Exam, na.rm=T))


# moyenne exam par groupes (en fonction nbre élèves total du groupe)
exam_per_group <- grades |>
  group_by(Group) |>
  count(Exam)

exam_per_group_2 <- inner_join(exam_per_group, nber_stdts_group, by = join_by(Group), suffix = c("_exam", "_students"))

mean_exam_per_group <- exam_per_group_2 |> group_by(Group) |> mutate(mean_exam = sum(Exam, na.rm=T)/n_students)

mean_exam_per_group2 <- mean_exam_per_group |> select(Group, mean_exam)

#pour selectionner lignes uniques ? |> slice(Group, 1,21,32,47,64,82,99,116,132,152,171,189,203,223,243,261,281,300,320,335,350,363,383,401)
```

```{r}
mean_exam_missed_mcq <- inner_join(average_exam_per_group, p_na_mcq_group3)
```

```{r}
set.seed(30)
mean_exam_missed_mcq |> ggplot(aes(x = P_missed, y = mean_exam, color = mean_exam, size = P_missed)) +
  geom_jitter(alpha = 0.5, width = 0.01, height = 0.01) +
  xlab("percentage of missed MCQ_xx grade per group") +
  ylab("average grade at the Exam per group") +
  scale_size_continuous("average grade at the Exam per group") +
  scale_color_viridis_c("percentage of missed MCQ_xx grade per group")
```

